version: '3.3'

volumes:
  static:
  media:
  postgres_data:


services:
  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: markeeee3/foodgram_backend:latest
    env_file:
      - ../.env
    volumes:
      - static:/backend_static
      - media:/media

    depends_on:
      - db

  frontend:
    image: markeeee3/foodgram_frontend:latest
    env_file:
      - ../.env
    volumes:
      - static:/app/result_build

  nginx:
    image: nginx:1.19.3
    env_file:
      - ../.env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/static/api/docs
      - static:/static
      - media:/media
    depends_on:
      - backend
